# -*- coding: utf-8 -*-

# What it does: Prints a message when either arrow tool button is pressed
# Wiring:       No wiring needed (GUI application)
# Expected output: A window with left and right arrow buttons, "Left" or "Right" is printed
# Tested on:    WalnutPi 2B / WalnutPi CM2
# Tutorial:     https://wiki.walnutpi.com/en/docs/walnutpi_2/pyQT5/widgets/buttons/tool_button

# Form implementation generated from reading ui file 'ToolButton.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(180, 130, 50, 50))
        self.toolButton.setArrowType(QtCore.Qt.LeftArrow)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(290, 130, 50, 50))
        self.toolButton_2.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_2.setObjectName("toolButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolButton.clicked.connect(self.fun1)     # Run fun1 when pressed
        self.toolButton_2.clicked.connect(self.fun2)   # Run fun2 when pressed
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))

    # Function executed when tool button 1 is pressed
    def fun1(self):
        print('Left')

    # Function executed when tool button 2 is pressed
    def fun2(self):
        print('Right')

#################
#  Main program #
#################
import sys

# [Optional] Allow Thonny to run remotely
import os
os.environ["DISPLAY"] = ":0.0"

# [Optional] Fix missing display on 2K+ resolution monitors
QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)

# Main entry, build and show the window
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()   # Create the window object
ui = Ui_MainWindow()                   # Create the window object designed with PyQt5
ui.setupUi(MainWindow)                 # Initialize the window
MainWindow.show()                      # Show the window

# [Recommended] Allow the terminal to interrupt the window with Ctrl+C for easier debugging
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)
timer = QtCore.QTimer()
timer.start(100)   # You may change this if you wish
timer.timeout.connect(lambda: None)   # Let the interpreter run each 100 ms

sys.exit(app.exec_())   # Exit the process when the window closes
